<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_SingleDrive_Conveyor_With_Out_Sensor_And_Stopper" Id="{58c91069-80ff-485d-ae0c-46ae716cb6b6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SingleDrive_Conveyor_With_Out_Sensor_And_Stopper EXTENDS FB_SingleDrive_Conveyor_With_Out_Sensor

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>